#!/usr/bin/env python3
"""
Concierge interactive simulator (terminal).

Two modes:

  Interactive (default) — type partner messages, see concierge replies inline,
  save the session to an xlsx whenever you want.

  Validation (--validate) — replay every fixture in
  tests/fixtures/concierge_replay.yaml, generate the next concierge reply with
  the new prompt, and dump everything to xlsx in the production conversation
  schema (one sheet, conversation-level metadata only on the first row of each
  conversation, message_window.* fields per row).

Output xlsx schema (matches the production conversation export):
  conversation_id, partner_id, first_name, last_name, zone_description,
  phone_number, start_date, started_at, last_message_at, total_message_count,
  status, partner_msg_count, agent_msg_count,
  message_window.confidence, message_window.content, message_window.created_at,
  message_window.intent_classified, message_window.llm_model,
  message_window.message_id, message_window.role,
  message_window.tokens_in, message_window.tokens_out

Usage:
  python3 scripts/simulate_concierge.py
  python3 scripts/simulate_concierge.py --name Walter
  python3 scripts/simulate_concierge.py --validate
  python3 scripts/simulate_concierge.py --validate --out tests/simulations/spec-validation.xlsx

Interactive commands at the partner-message prompt:
  :name <first_name>     set/change the partner's first name
  :system <text>         seed a concierge message into history (no LLM call)
  :reset [label]         finish current run, start a new one
  :save [path.xlsx]      write all runs in this session to xlsx
  :show                  print current run transcript
  :runs                  list all runs in this session
  :prompt                dump the full prompt that would be sent next turn
  :model <name>          haiku | sonnet | opus
  :help                  show this help
  :quit / :q             exit (auto-saves if --out provided)
"""

from __future__ import annotations

import argparse
import asyncio
import datetime as dt
import os
import sys
import uuid
from datetime import datetime
from pathlib import Path

WORKSPACE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(WORKSPACE))

import yaml  # noqa: E402
from openpyxl import Workbook  # noqa: E402
from openpyxl.styles import Alignment, Font, PatternFill  # noqa: E402
from openpyxl.utils import get_column_letter  # noqa: E402

from server.config import CLAUDE_CLI_PATH  # noqa: E402
from server.services.draft_service import assemble_prompt  # noqa: E402

DEFAULT_MODEL = "haiku"
TIMEOUT_SEC = 120
SIMULATIONS_DIR = WORKSPACE / "tests" / "simulations"
FIXTURES_PATH = WORKSPACE / "tests" / "fixtures" / "concierge_replay.yaml"

# Production model used for original conversation history (gemini-2.5-flash).
# New replies generated by this simulator are tagged with the local replay
# model identifier so reviewers can tell them apart in the xlsx.
PROD_MODEL_TAG = "gemini-2.5-flash"
LOCAL_MODEL_TAG = {
    "haiku": "claude-haiku-4-5-20251001",
    "sonnet": "claude-sonnet-4-6",
    "opus": "claude-opus-4-7",
}


def now_ts() -> str:
    return dt.datetime.now().strftime("%Y%m%d-%H%M%S")


def fmt_dt(d: datetime) -> str:
    """Match production export format like '4/29/2026 13:46:10'."""
    return f"{d.month}/{d.day}/{d.year} {d.hour}:{d.minute:02d}:{d.second:02d}"


async def run_claude(prompt: str, model: str) -> tuple[str, str, int]:
    proc = await asyncio.create_subprocess_exec(
        CLAUDE_CLI_PATH, "-p", "--model", model,
        stdin=asyncio.subprocess.PIPE,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    try:
        stdout, stderr = await asyncio.wait_for(
            proc.communicate(input=prompt.encode()),
            timeout=TIMEOUT_SEC,
        )
    except asyncio.TimeoutError:
        proc.kill()
        return "", "TIMEOUT", -1
    return stdout.decode("utf-8", errors="replace"), stderr.decode("utf-8", errors="replace"), proc.returncode


def clean_output(raw: str) -> str:
    s = raw.strip()
    if len(s) >= 2 and s[0] in ('"', "'", "`") and s[-1] == s[0]:
        s = s[1:-1].strip()
    if s.startswith("```"):
        lines = s.split("\n")[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        s = "\n".join(lines).strip()
    return s


def to_messages(history: list[dict]) -> list[dict]:
    return [
        {"direction": "inbound" if h["role"] == "partner" else "outbound",
         "content": h["content"],
         "ts": h["ts"]}
        for h in history
    ]


# ─────────────────────── conversation → row records ───────────────────────

# Production-schema column order (must match exactly)
COLUMNS = [
    "conversation_id",
    "partner_id",
    "first_name",
    "last_name",
    "zone_description",
    "phone_number",
    "start_date",
    "started_at",
    "last_message_at",
    "total_message_count",
    "status",
    "partner_msg_count",
    "agent_msg_count",
    "message_window.confidence",
    "message_window.content",
    "message_window.created_at",
    "message_window.intent_classified",
    "message_window.llm_model",
    "message_window.message_id",
    "message_window.role",
    "message_window.tokens_in",
    "message_window.tokens_out",
]


def conversation_to_rows(convo: dict) -> list[dict]:
    """Convert one conversation dict (with metadata + messages) into a list of
    xlsx row dicts matching the production schema. Conversation-level fields
    appear only on the FIRST row; subsequent rows leave those blank."""
    msgs = convo["history"]
    partner_count = sum(1 for m in msgs if m["role"] == "partner")
    agent_count = sum(1 for m in msgs if m["role"] == "concierge")

    last_ts = msgs[-1]["ts_pretty"] if msgs else convo.get("started_at", "")

    rows = []
    for i, m in enumerate(msgs):
        is_first = (i == 0)
        row = {col: "" for col in COLUMNS}
        if is_first:
            row["conversation_id"] = convo.get("conversation_id", "")
            row["partner_id"] = convo.get("partner_id", "")
            row["first_name"] = convo.get("first_name", "")
            row["last_name"] = convo.get("last_name", "")
            row["zone_description"] = convo.get("zone_description", "")
            row["phone_number"] = convo.get("phone_number", "")
            row["start_date"] = convo.get("start_date", "")
            row["started_at"] = convo.get("started_at", "")
            row["last_message_at"] = last_ts
            row["total_message_count"] = len(msgs)
            row["status"] = convo.get("status", "")
            row["partner_msg_count"] = partner_count
            row["agent_msg_count"] = agent_count

        row["message_window.content"] = m["content"] or "(empty — stop-replying rule fired)"
        row["message_window.created_at"] = m["ts_pretty"]
        row["message_window.message_id"] = m["message_id"]
        row["message_window.role"] = "user" if m["role"] == "partner" else "assistant"

        if m["role"] == "concierge":
            row["message_window.confidence"] = m.get("confidence", "")
            row["message_window.intent_classified"] = m.get("intent", "")
            row["message_window.llm_model"] = m.get("model_tag", "")
            row["message_window.tokens_in"] = m.get("tokens_in", "")
            row["message_window.tokens_out"] = m.get("tokens_out", "")

        rows.append(row)
    return rows


# ─────────────────────── xlsx export ───────────────────────

HEADER_FILL = PatternFill("solid", fgColor="DDDDDD")
ROLE_PARTNER_FILL = PatternFill("solid", fgColor="EAF6FF")
ROLE_CONCIERGE_FILL = PatternFill("solid", fgColor="F4F4F4")
NEW_REPLY_FILL = PatternFill("solid", fgColor="FFF6CC")  # highlight new system replies


def export_xlsx(conversations: list[dict], path: Path):
    wb = Workbook()
    ws = wb.active
    ws.title = "Conversations"

    # Header
    ws.append(COLUMNS)
    for col_idx in range(1, len(COLUMNS) + 1):
        cell = ws.cell(row=1, column=col_idx)
        cell.font = Font(bold=True)
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(vertical="top", wrap_text=True)

    # Body
    row_idx = 2
    for convo in conversations:
        rows = conversation_to_rows(convo)
        for i, row in enumerate(rows):
            for col_idx, col in enumerate(COLUMNS, start=1):
                cell = ws.cell(row=row_idx, column=col_idx, value=row.get(col, ""))
                cell.alignment = Alignment(vertical="top", wrap_text=True)
            # Determine fill
            msg = convo["history"][i]
            if msg.get("is_new_reply"):
                fill = NEW_REPLY_FILL
            elif msg["role"] == "partner":
                fill = ROLE_PARTNER_FILL
            else:
                fill = ROLE_CONCIERGE_FILL
            for col_idx in range(1, len(COLUMNS) + 1):
                ws.cell(row=row_idx, column=col_idx).fill = fill
            row_idx += 1

    # Column widths — content column wider, ID/timestamp columns reasonable
    widths = {
        "conversation_id": 38,
        "partner_id": 38,
        "first_name": 12,
        "last_name": 12,
        "zone_description": 18,
        "phone_number": 14,
        "start_date": 11,
        "started_at": 22,
        "last_message_at": 22,
        "total_message_count": 8,
        "status": 14,
        "partner_msg_count": 8,
        "agent_msg_count": 8,
        "message_window.confidence": 7,
        "message_window.content": 80,
        "message_window.created_at": 22,
        "message_window.intent_classified": 22,
        "message_window.llm_model": 24,
        "message_window.message_id": 38,
        "message_window.role": 10,
        "message_window.tokens_in": 9,
        "message_window.tokens_out": 9,
    }
    for col_idx, col in enumerate(COLUMNS, start=1):
        ws.column_dimensions[get_column_letter(col_idx)].width = widths.get(col, 14)

    ws.freeze_panes = "A2"

    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)


# ─────────────────────── interactive loop ───────────────────────


def render_terminal_run(convo: dict) -> str:
    lines = [f"=== Run: {convo.get('label') or '(unnamed)'} | partner={convo.get('first_name', '?')} ==="]
    for i, h in enumerate(convo["history"], 1):
        role = "Partner" if h["role"] == "partner" else "Concierge"
        meta = ""
        if h["role"] == "concierge" and h.get("latency"):
            meta = f"  [{h['latency']:.1f}s, {h.get('model_tag', '?')}]"
        body = h["content"] if h["content"] else "(empty — stop-replying rule fired)"
        lines.append(f"  {i}. {role}{meta}:")
        for ln in body.splitlines() or [""]:
            lines.append(f"      {ln}")
    return "\n".join(lines)


def make_synthetic_convo(first_name: str, model: str, label: str = "") -> dict:
    """For interactive runs without real production metadata."""
    return {
        "label": label,
        "conversation_id": str(uuid.uuid4()),
        "partner_id": str(uuid.uuid4()),
        "first_name": first_name,
        "last_name": "",
        "zone_description": "(simulator)",
        "phone_number": "",
        "start_date": fmt_dt(dt.datetime.now()).split(" ")[0],
        "started_at": fmt_dt(dt.datetime.now()),
        "status": "answering_qs",
        "model": model,
        "history": [],
    }


async def interactive(args):
    first_name = args.name or ""
    model = args.model
    runs: list[dict] = []
    current_run = make_synthetic_convo(first_name, model, args.label or "")
    runs.append(current_run)
    out_path = Path(args.out) if args.out else None

    print("=" * 78)
    print(f"Concierge Simulator — model={model}")
    print(f"  Partner first name: {first_name or '(unset)'}")
    print(f"  Default save dir:   {SIMULATIONS_DIR}")
    print("=" * 78)
    print("Type partner messages and hit enter. :help for commands, :quit to exit.")
    print("Tip: seed the concierge welcome with    :system Hi Walter! Welcome to Shiftsmart...")
    print()

    while True:
        try:
            user_input = input("partner> ").rstrip("\n")
        except (EOFError, KeyboardInterrupt):
            print()
            break

        if not user_input:
            continue

        if user_input.startswith(":"):
            cmd, _, rest = user_input.partition(" ")
            cmd = cmd.lower()

            if cmd in (":quit", ":q", ":exit"):
                break
            elif cmd == ":help":
                print(__doc__)
            elif cmd == ":name":
                first_name = rest.strip()
                current_run["first_name"] = first_name
                print(f"  → first_name set to {first_name!r}")
            elif cmd == ":system":
                seeded = rest.strip()
                if not seeded:
                    print("  → :system requires text")
                    continue
                ts = dt.datetime.now()
                current_run["history"].append({
                    "role": "concierge",
                    "content": seeded,
                    "ts": ts.isoformat(timespec="seconds"),
                    "ts_pretty": fmt_dt(ts),
                    "message_id": str(uuid.uuid4()),
                    "model_tag": "(seeded)",
                    "latency": None,
                })
                print(f"  → seeded outbound message ({len(seeded)} chars)")
            elif cmd == ":reset":
                if not current_run["history"]:
                    current_run["label"] = rest.strip()
                else:
                    print(f"  → finishing run #{len(runs)} ({len(current_run['history'])} turns), starting new run")
                    current_run = make_synthetic_convo(first_name, model, rest.strip())
                    runs.append(current_run)
            elif cmd == ":save":
                target = rest.strip() or str(SIMULATIONS_DIR / f"sim-{now_ts()}.xlsx")
                if not target.endswith(".xlsx"):
                    target += ".xlsx"
                path = Path(target)
                non_empty = [r for r in runs if r["history"]]
                if not non_empty:
                    print("  → no turns to save")
                    continue
                export_xlsx(non_empty, path)
                print(f"  → saved {len(non_empty)} run(s) to {path}")
                if out_path is None:
                    out_path = path
            elif cmd == ":show":
                print(render_terminal_run(current_run))
            elif cmd == ":runs":
                for i, r in enumerate(runs, 1):
                    marker = " *" if r is current_run else "  "
                    label = r.get("label") or "(unnamed)"
                    print(f"  {marker} #{i}: {label} | {r.get('first_name', '?')} | {len(r['history'])} turns")
            elif cmd == ":prompt":
                msgs = to_messages(current_run["history"])
                prompt = assemble_prompt(msgs, first_name, "")
                print(f"\n--- ASSEMBLED PROMPT ({len(prompt)} chars) ---\n")
                print(prompt)
                print("\n--- END PROMPT ---\n")
            elif cmd == ":model":
                if rest.strip() in ("haiku", "sonnet", "opus"):
                    model = rest.strip()
                    current_run["model"] = model
                    print(f"  → model set to {model}")
                else:
                    print(f"  → unknown model {rest.strip()!r} — use haiku|sonnet|opus")
            else:
                print(f"  → unknown command {cmd!r}, try :help")
            continue

        # Real partner message
        ts_partner = dt.datetime.now()
        current_run["history"].append({
            "role": "partner",
            "content": user_input,
            "ts": ts_partner.isoformat(timespec="seconds"),
            "ts_pretty": fmt_dt(ts_partner),
            "message_id": str(uuid.uuid4()),
        })

        msgs = to_messages(current_run["history"])
        prompt = assemble_prompt(msgs, first_name, "")
        if not prompt:
            print("  → assemble_prompt returned empty, skipping")
            continue

        t0 = dt.datetime.now().timestamp()
        stdout, stderr, code = await run_claude(prompt, model)
        latency = dt.datetime.now().timestamp() - t0
        reply = clean_output(stdout)

        if code != 0 and not reply:
            print(f"  ERROR (code={code}): {stderr[:300]}")
            current_run["history"].pop()
            continue

        ts_reply = dt.datetime.now()
        current_run["history"].append({
            "role": "concierge",
            "content": reply,
            "ts": ts_reply.isoformat(timespec="seconds"),
            "ts_pretty": fmt_dt(ts_reply),
            "message_id": str(uuid.uuid4()),
            "model_tag": LOCAL_MODEL_TAG.get(model, model),
            "latency": latency,
            "is_new_reply": True,
        })

        if reply:
            print(f"\nconcierge ({latency:.1f}s): {reply}\n")
        else:
            print(f"\nconcierge ({latency:.1f}s): (empty — stop-replying rule fired)\n")

        if out_path:
            export_xlsx([r for r in runs if r["history"]], out_path)

    non_empty = [r for r in runs if r["history"]]
    if non_empty:
        if not out_path:
            out_path = SIMULATIONS_DIR / f"sim-{now_ts()}.xlsx"
        export_xlsx(non_empty, out_path)
        print(f"\nFinal session saved: {len(non_empty)} run(s) → {out_path}")


# ─────────────────────── validation mode ───────────────────────


async def validate_mode(args):
    """Replay every fixture and write a production-schema xlsx."""
    if not FIXTURES_PATH.exists():
        print(f"ERROR: fixtures not found at {FIXTURES_PATH}", file=sys.stderr)
        sys.exit(2)
    with open(FIXTURES_PATH) as f:
        data = yaml.safe_load(f)
    fixtures = data.get("fixtures", [])

    if args.filters:
        fixtures = [f for f in fixtures
                    if any(s.lower() in (f.get("name", "") + f.get("partner_id", "")).lower()
                           for s in args.filters)]
    if not fixtures:
        print("No fixtures matched filters")
        sys.exit(2)

    out_path = Path(args.out) if args.out else SIMULATIONS_DIR / f"validation-{now_ts()}.xlsx"
    print(f"Running validation on {len(fixtures)} fixture(s) — model={args.model}, concurrency={args.concurrency}")
    print("Output: " + str(out_path))
    print("-" * 78)

    sem = asyncio.Semaphore(args.concurrency)

    async def run_one(fx):
        async with sem:
            convo = await replay_fixture(fx, args.model)
        return convo

    conversations = await asyncio.gather(*[run_one(fx) for fx in fixtures])

    # Print inline results so user sees them BEFORE writing
    print()
    for fx, convo in zip(fixtures, conversations):
        new_reply = next((m for m in reversed(convo["history"]) if m.get("is_new_reply")), None)
        latency = new_reply.get("latency", 0) if new_reply else 0
        reply_text = new_reply["content"] if new_reply else ""
        if not reply_text:
            reply_text = "(empty — stop-replying rule fired)"
        # Trim for terminal
        single_line = reply_text.replace("\n", " ⏎ ")
        if len(single_line) > 130:
            single_line = single_line[:127] + "..."
        print(f"\n● {fx['name']} ({latency:.1f}s)")
        print(f"   partner: {convo['first_name']} {convo.get('last_name', '')} | {convo.get('zone_description', '')}")
        last_partner = next((m for m in reversed(convo["history"][:-1]) if m["role"] == "partner"), None)
        if last_partner:
            lp = last_partner["content"]
            if len(lp) > 100:
                lp = lp[:97] + "..."
            print(f"   last partner msg: {lp!r}")
        print(f"   new concierge reply: {single_line}")

    print("\n" + "-" * 78)
    print(f"Writing xlsx → {out_path}")
    export_xlsx(conversations, out_path)
    print(f"Done. {len(conversations)} conversations written.")


async def replay_fixture(fx: dict, model: str) -> dict:
    """Run one fixture: replay the conversation history, generate a new
    concierge reply with the local prompt, return the convo dict ready for
    xlsx export."""
    # Parse the start timestamp; messages get monotonic offsets from there
    start_ts = parse_pretty_ts(fx.get("started_at", "")) or dt.datetime.now()

    history = []
    for i, m in enumerate(fx["messages"]):
        ts = start_ts + dt.timedelta(seconds=30 * i)
        is_partner = (m["from"] == "partner")
        history.append({
            "role": "partner" if is_partner else "concierge",
            "content": m["content"],
            "ts": ts.isoformat(timespec="seconds"),
            "ts_pretty": fmt_dt(ts),
            "message_id": str(uuid.uuid4()),
            "model_tag": "" if is_partner else PROD_MODEL_TAG,
        })

    # Build prompt + call Claude to generate the new concierge reply
    prompt = assemble_prompt(to_messages(history), fx.get("first_name", ""), "")
    t0 = dt.datetime.now().timestamp()
    stdout, _stderr, _code = await run_claude(prompt, model)
    latency = dt.datetime.now().timestamp() - t0
    reply = clean_output(stdout)

    ts_reply = start_ts + dt.timedelta(seconds=30 * len(history))
    history.append({
        "role": "concierge",
        "content": reply,
        "ts": ts_reply.isoformat(timespec="seconds"),
        "ts_pretty": fmt_dt(ts_reply),
        "message_id": str(uuid.uuid4()),
        "model_tag": LOCAL_MODEL_TAG.get(model, model),
        "latency": latency,
        "is_new_reply": True,
    })

    convo = {
        "label": fx["name"],
        "conversation_id": fx.get("conversation_id", str(uuid.uuid4())),
        "partner_id": fx.get("partner_id", ""),
        "first_name": fx.get("first_name", ""),
        "last_name": fx.get("last_name", ""),
        "zone_description": fx.get("zone_description", ""),
        "phone_number": fx.get("phone_number", ""),
        "start_date": fx.get("start_date", ""),
        "started_at": fx.get("started_at", ""),
        "status": fx.get("status", ""),
        "model": model,
        "history": history,
    }
    return convo


def parse_pretty_ts(s: str) -> datetime | None:
    """Parse '4/29/2026 9:37:16' → datetime."""
    if not s:
        return None
    try:
        return datetime.strptime(s, "%m/%d/%Y %H:%M:%S")
    except ValueError:
        try:
            return datetime.strptime(s, "%m/%d/%Y %H:%M")
        except ValueError:
            return None


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--name", default="", help="(interactive) partner first name")
    parser.add_argument("--model", default=DEFAULT_MODEL, help="haiku | sonnet | opus")
    parser.add_argument("--label", default="", help="(interactive) label for first run")
    parser.add_argument("--out", default=None, help="output xlsx path")
    parser.add_argument("--validate", action="store_true",
                        help="replay all fixtures and write a production-schema xlsx")
    parser.add_argument("--concurrency", type=int, default=4,
                        help="(--validate only) parallel fixture runs")
    parser.add_argument("filters", nargs="*",
                        help="(--validate only) substrings to filter fixtures")
    args = parser.parse_args()

    if args.validate:
        asyncio.run(validate_mode(args))
    else:
        asyncio.run(interactive(args))


if __name__ == "__main__":
    main()
